[workspace]
resolver = "2"
members = [
    "tpt-torus-sys",
    "tpt-torus-core",
    "tpt-torus-backend-uring",
    "tpt-torus-backend-iocp",
    "tpt-torus-backend-kqueue",
    "tpt-torus-cxx",
    "tpt-torus-hw",
    "torus-rs",
    "cargo-torus-new",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.87.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/tpt-solutions/tpt-torus"
homepage = "https://github.com/tpt-solutions/tpt-torus"
