[package]
name = "tpt-torus-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "The Virtual Torus abstraction, Safe API, and Torus handle."
readme = "README.md"
keywords = ["async-io", "io_uring", "iocp", "kqueue", "io"]
categories = ["asynchronous", "os"]

[lib]
name = "tpt_torus_core"
path = "src/lib.rs"

[dependencies]
libc = "0.2"
tracing = { version = "0.1", optional = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
tpt-torus-backend-uring = { path = "../tpt-torus-backend-uring", version = "0.1.0" }
tpt-torus-backend-iocp = { path = "../tpt-torus-backend-iocp", version = "0.1.0" }
tpt-torus-backend-kqueue = { path = "../tpt-torus-backend-kqueue", version = "0.1.0" }

[features]
default = []
tracing = ["dep:tracing"]

[[bench]]
name = "torus_bench"
harness = false
