[package]
name = "tpt-torus-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "The Virtual Torus abstraction, Safe API, and Torus handle."
readme = "README.md"
keywords = ["async-io", "io_uring", "iocp", "kqueue", "io"]
categories = ["asynchronous", "os"]

[lib]
name = "tpt_torus_core"
path = "src/lib.rs"

[dependencies]
libc = "0.2"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "torus_bench"
harness = false
